apiVersion: v1
kind: Pod
metadata: 
  name: nginx
  labels:
    project: roboshop
    environment: dev
    purpose: poc
spec:
  containers:
    - name: nginx   # container name
      image: nginx  # by default it will pull the latest image from docker hub