apiVersion: v1
kind: Pod
metadata:
  name: annotations
  labels:
    project: roboshop
  annotations:
    imageregistry: "https://hub.docker.com"
    jenkins-build-url: "https://jenkins.roboshop.com/job/roboshop/job/dev/job/devops90s/job/2"
  spec:
    containers:
    - name: nginx
      image: nginx