apiVersion: v1
kind: Pod
metadata:
  name: resources
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits: #hard limit
          memory: "256Mi"
          cpu: "150m"